-- MySQL Script generated by MySQL Workbench
-- Mon Mar 16 14:29:29 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`endestabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`endestabelecimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cep` VARCHAR(10) NOT NULL,
  `uf` VARCHAR(4) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `logradouro` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `numEdificio` VARCHAR(9) NOT NULL,
  `numComplemento` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `dataNascimento` VARCHAR(10) NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(30) NULL,
  `senha` VARCHAR(45) NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`estabelecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`estabelecimento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cnpj` VARCHAR(18) NOT NULL,
  `nomeFantasia` VARCHAR(45) NOT NULL,
  `inscEstadual` VARCHAR(15) NOT NULL,
  `telefone` VARCHAR(30) NOT NULL,
  `idEndereco` INT NOT NULL,
  `idProprietario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Estabelecimento_EnderecoEstabelecimento1_idx` (`idEndereco` ASC) VISIBLE,
  INDEX `fk_Estabelecimento_Usuario1_idx` (`idProprietario` ASC) VISIBLE,
  CONSTRAINT `fk_Estabelecimento_EnderecoEstabelecimento1`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `mydb`.`endestabelecimento` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Estabelecimento_Usuario1`
    FOREIGN KEY (`idProprietario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcao` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NOT NULL,
  `nivelPermissao` VARCHAR(11) NOT NULL,
  `idEstabelecimento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Funcao_Estabelecimento1_idx` (`idEstabelecimento` ASC) VISIBLE,
  CONSTRAINT `fk_Funcao_Estabelecimento1`
    FOREIGN KEY (`idEstabelecimento`)
    REFERENCES `mydb`.`estabelecimento` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `idFuncao` INT NOT NULL,
  `cpf` VARCHAR(14) NOT NULL,
  `statusConta` INT(1) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `dataNascimento` VARCHAR(10) NULL,
  `email` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(30) NULL,
  `senha` VARCHAR(45) NOT NULL,
  `idEstabelecimento` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Funcionario_Funcao1_idx` (`idFuncao` ASC) VISIBLE,
  INDEX `fk_Funcionario_Estabelecimento1_idx` (`idEstabelecimento` ASC) VISIBLE,
  CONSTRAINT `fk_Funcionario_Funcao1`
    FOREIGN KEY (`idFuncao`)
    REFERENCES `mydb`.`funcao` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Funcionario_Estabelecimento1`
    FOREIGN KEY (`idEstabelecimento`)
    REFERENCES `mydb`.`estabelecimento` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`prato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prato` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` TEXT NOT NULL,
  `dataCriacao` DATE NOT NULL,
  `imagemUrl` TEXT NULL,
  `preco` FLOAT NOT NULL,
  `exibir` INT(1) NOT NULL,
  `idEstabelecimento` INT NOT NULL,
  `idFuncionario` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Prato_Estabelecimento1_idx` (`idEstabelecimento` ASC) VISIBLE,
  INDEX `fk_Prato_Funcionario1_idx` (`idFuncionario` ASC) VISIBLE,
  CONSTRAINT `fk_Prato_Estabelecimento1`
    FOREIGN KEY (`idEstabelecimento`)
    REFERENCES `mydb`.`estabelecimento` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Prato_Funcionario1`
    FOREIGN KEY (`idFuncionario`)
    REFERENCES `mydb`.`funcionario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comanda` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATE NOT NULL,
  `hora` VARCHAR(5) NOT NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Comanda_Usuario_idx` (`idCliente` ASC) VISIBLE,
  CONSTRAINT `fk_Comanda_Usuario`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pedido` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantidade` INT NOT NULL,
  `idComanda` INT NOT NULL,
  `idPrato` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Pedido_Comanda1_idx` (`idComanda` ASC) VISIBLE,
  INDEX `fk_Pedido_Prato1_idx` (`idPrato` ASC) VISIBLE,
  CONSTRAINT `fk_Pedido_Comanda1`
    FOREIGN KEY (`idComanda`)
    REFERENCES `mydb`.`comanda` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_Pedido_Prato1`
    FOREIGN KEY (`idPrato`)
    REFERENCES `mydb`.`prato` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
